"""Recovery figure: can AutoCog recover the *randomized-cue TTB* model?

The "TTB" synthetic data was generated by an old ttb.yaml whose validity spec
was '[(0.0, 1.0)] * n_features' -- a FRESH random validity vector per subject.
That randomizes TTB's cue order, so the first discriminating cue is uniform over
the discriminating set. We call this generator the "randomized-cue TTB": a
coherent but non-standard model (not in the heuristics literature, which assumes
a fixed validity order).

This script asks the recovery question against that true model, mirroring
recovery_correlation.py's layout: x = action-noise level (ε ∈ {0.0, 0.05, 0.3}),
grouped bars per role in the SAME order, mean ± SEM across the runs at each
noise level. Two panels (Correlation, MSE).

  seed              : the round-0 starting competitor theories      (ε=0)
  surfaced (mean)   : all AutoCog-surfaced models                    (ε=0)
  surfaced (best)   : best single surfaced model per run (post hoc) (ε=0)
  randomized cue TTB: the model itself, replayed WITH the run's action noise
                      (recovery ceiling; target is itself at ε=0)

One experiment (round 0, obs 0) per run, on that experiment's own stimuli /
validities / rating_max. Base choice = argmax(predict); ε-greedy action noise
mirrors src/experiment.py:173. Validities are NOT re-pinned (each theory draws
its own per its spec).
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import numpy as np

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))
from src.theory import Theory                                  # noqa: E402
from scripts.eval_hilbig import (                              # noqa: E402
    resolve_base_theories, resolve_surfaced_theories,
)

YAML_DIR = _REPO / "theories" / "heuristic_decision_making"
EMPTY_HISTORY = {"stimulus": [], "label": [],
                 "previous_stimuli": [], "previous_labels": []}
TTB_ROOT = _REPO / "results/synthetic_cardinal/ttb"
OUT_PNG = (_REPO / "results/synthetic_cardinal/"
           "recovery_randomized_cue_ttb.png")
NOISES = (0.0, 0.05, 0.3)
N_SUBJ_TARGET = 2000   # MC estimate of the true model's noiseless proportions
N_SUBJ_MODEL = 400


def load_experiment(run_dir, round_idx=0, obs_idx=0):
    st = json.loads((run_dir / "observations" / "state.json").read_text())
    obs = st["rounds"][round_idx]["observations"][obs_idx]
    exp = obs["experiment"]
    data_file = next((run_dir / "observations" / "data").glob(
        f"round_{round_idx:03d}_obs_{obs_idx:02d}.jsonl"))
    return exp, data_file


def unique_pairs(data_file):
    seen, order = set(), []
    for line in Path(data_file).read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        a = tuple(int(x) for x in rec["option_a_ratings"])
        b = tuple(int(x) for x in rec["option_b_ratings"])
        if (a, b) not in seen:
            seen.add((a, b)); order.append((a, b))
    return order


def sim_pb(theory, pairs, *, validities, rating_max, n_subj, seed,
           action_noise=0.0):
    """Per-stimulus P(choose B) over n_subj param draws. Base choice =
    argmax(predict); with prob `action_noise` the choice is a uniform coin
    (ε-greedy action noise, mirroring src/experiment.py:173)."""
    random.seed(seed)
    noise_rng = np.random.default_rng(seed)
    ctx = {"n_features": len(validities), "n_labels": 2,
           "validities": list(validities), "rating_max": int(rating_max)}
    acc = np.zeros(len(pairs))
    for _ in range(n_subj):
        params = theory.sample_parameters(ctx)
        for j, (a, b) in enumerate(pairs):
            probs = np.asarray(theory.predict(
                params, np.array([a, b], dtype=float), EMPTY_HISTORY))
            if action_noise > 0.0 and noise_rng.random() < action_noise:
                acc[j] += int(noise_rng.integers(0, len(probs)))
            else:
                acc[j] += int(np.argmax(probs))
    return acc / n_subj


def pearson(x, y):
    x = np.asarray(x); y = np.asarray(y)
    if x.std() == 0 or y.std() == 0:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def mse(x, y):
    return float(np.mean((np.asarray(x) - np.asarray(y)) ** 2))


# {metric: {noise: {role: [per-run values]}}}
def _push(store, noise, role, val):
    store.setdefault(noise, {}).setdefault(role, []).append(val)


def main():
    rand_ttb = Theory.from_yaml(YAML_DIR / "ttb.yaml")
    rand_ttb.parameters["validities"] = "[(0.0, 1.0)] * n_features"

    agg_r: dict[float, dict[str, list[float]]] = {}
    agg_m: dict[float, dict[str, list[float]]] = {}

    # Discover noise dirs from disk (dir names are literal, e.g. "noise=0.0").
    noise_dirs = {float(d.name.removeprefix("noise=")): d
                  for d in sorted(TTB_ROOT.glob("noise=*")) if d.is_dir()}
    for noise in NOISES:
        noise_dir = noise_dirs.get(noise)
        runs = sorted(noise_dir.glob("hdm_ground_truth_ttb_*_run*")) if noise_dir else []
        print(f"=== noise={noise:g}  ({len(runs)} runs)")
        for run in runs:
            exp, data_file = load_experiment(run)
            validities = [float(v) for v in exp["validities"]]
            rating_max = int(exp["rating_max"])
            pairs = unique_pairs(data_file)

            # TARGET = randomized-cue TTB, noiseless, independent seed.
            target = sim_pb(rand_ttb, pairs, validities=validities,
                            rating_max=rating_max, n_subj=N_SUBJ_TARGET,
                            seed=999)

            # gt bar: randomized-cue TTB replayed WITH this run's action noise.
            gt = sim_pb(rand_ttb, pairs, validities=validities,
                        rating_max=rating_max, n_subj=N_SUBJ_MODEL, seed=0,
                        action_noise=noise)
            _push(agg_r, noise, "gt", pearson(gt, target))
            _push(agg_m, noise, "gt", mse(gt, target))

            # seed + surfaced bars: replayed at ε=0. Pool theories within run.
            for role, theories in (("seed", resolve_base_theories(run)),
                                   ("surfaced", resolve_surfaced_theories(run))):
                rs, ms = [], []
                for th in theories.values():
                    try:
                        vec = sim_pb(th, pairs, validities=validities,
                                     rating_max=rating_max,
                                     n_subj=N_SUBJ_MODEL, seed=0)
                        rs.append(pearson(vec, target)); ms.append(mse(vec, target))
                    except Exception as e:  # noqa: BLE001
                        print(f"    !! {run.name} {role}: "
                              f"{type(e).__name__}: {e}")
                rs = [v for v in rs if not np.isnan(v)]
                ms = [v for v in ms if not np.isnan(v)]
                if rs:
                    _push(agg_r, noise, role, float(np.mean(rs)))
                    _push(agg_m, noise, role, float(np.mean(ms)))
                if role == "surfaced" and rs:
                    _push(agg_r, noise, "surfaced (best)", float(np.nanmax(rs)))
                    _push(agg_m, noise, "surfaced (best)", float(np.nanmin(ms)))
            print(f"    {run.name}: "
                  f"gt r={agg_r[noise]['gt'][-1]:+.3f} "
                  f"surf r={agg_r[noise]['surfaced'][-1]:+.3f}")
        print()

    plot_recovery(agg_r, agg_m, OUT_PNG)


# Same role order as recovery_correlation.py.
ROLE_ORDER = ("seed", "surfaced", "surfaced (best)", "gt")
ROLE_LABEL = {
    "seed": "seed", "surfaced": "surfaced",
    "surfaced (best)": "surfaced (best)", "gt": "randomized cue TTB",
}
ROLE_COLOR = {
    "seed": "#4C72B0", "surfaced": "#55A868",
    "surfaced (best)": "#1B7837", "gt": "#8172B2",
}


def _mean_sem(vals):
    vals = [v for v in vals if not np.isnan(v)]
    if not vals:
        return np.nan, 0.0
    m = float(np.mean(vals))
    s = float(np.std(vals, ddof=1) / np.sqrt(len(vals))) if len(vals) > 1 else 0.0
    return m, s


def plot_recovery(agg_r, agg_m, out_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    noises = sorted(agg_r)
    x = np.arange(len(noises))
    width = 0.8 / len(ROLE_ORDER)
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.4), sharex=True)

    for ax, agg, ylab, ttl in [
        (axes[0], agg_r, "Pearson r to randomized-cue TTB", "Correlation"),
        (axes[1], agg_m, "MSE to randomized-cue TTB (lower=better)", "MSE"),
    ]:
        for i, role in enumerate(ROLE_ORDER):
            means = np.array([_mean_sem(agg[n].get(role, []))[0]
                              for n in noises], dtype=float)
            sems = np.array([_mean_sem(agg[n].get(role, []))[1]
                             for n in noises], dtype=float)
            ax.bar(x - 0.4 + width * (i + 0.5), means, width,
                   yerr=sems, capsize=2, color=ROLE_COLOR[role],
                   edgecolor="black", linewidth=0.3,
                   label=ROLE_LABEL[role] if ax is axes[0] else None)
        ax.set_xticks(x)
        ax.set_xticklabels([f"{n:g}" for n in noises])
        ax.set_xlabel("ground-truth action noise (ε)")
        ax.set_ylabel(ylab)
        ax.set_title(ttl)
        ax.grid(axis="y", linestyle=":", linewidth=0.4, alpha=0.5)
        ax.set_axisbelow(True)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[0].axhline(0.0, color="0.4", linewidth=0.8)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=len(ROLE_ORDER),
               bbox_to_anchor=(0.5, -0.02), frameon=False)
    fig.suptitle("AutoCog recovers the randomized-cue TTB model "
                 "(TTB runs, mean ± SEM across runs)", fontsize=11)
    fig.tight_layout(rect=(0, 0.05, 1, 0.95))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[plot] wrote {out_path}")


if __name__ == "__main__":
    main()
