"""Which TTB actually generated each synthetic dataset?

For noise=0.0 we established the data was generated by the OLD ttb.yaml
(validities ~ '[(0.0,1.0)]*n_features', random per subject) = the
"randomized-cue TTB", NOT proper descending-validity (canonical) TTB. The
hypothesis here: maybe a LATER noise level (e.g. noise=0.3) was regenerated
with the corrected canonical TTB.

Same method as the noise=0.0 check: take the ACTUAL on-disk choices
(observations/data/*.jsonl) for one experiment per run, pool into empirical
P(B) per unique stimulus, and ask which candidate generator the data matches:

  canonical TTB      : proper descending-validity, one-reason TTB (the INTENDED
                       model). Uses the experiment's own real validities.
  randomized-cue TTB : old buggy spec, random per-subject validities (REFERENCE).

Both candidates are simulated WITH the run's action noise (ε), mirroring
src/experiment.py:173, so MSE is on equal footing with the noisy data;
correlation is ε-robust by construction. choice = argmax(predict); validities
NOT re-pinned (each spec draws its own from the supplied context).

If a noise level used canonical TTB, DATA-vs-canonical should be high (r→1,
low MSE) and DATA-vs-randomized low/negative. noise=0.0 is the control: there
DATA matches randomized-cue, not canonical.

Output: results/.../ttb_generator_check.png (grouped bars, x = noise level,
bars = {data vs canonical TTB, data vs randomized-cue TTB}; Correlation + MSE).
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import numpy as np

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))
from src.theory import Theory  # noqa: E402

YAML_DIR = _REPO / "theories" / "heuristic_decision_making"
EMPTY_HISTORY = {"stimulus": [], "label": [],
                 "previous_stimuli": [], "previous_labels": []}
TTB_ROOT = _REPO / "results/synthetic_cardinal/ttb"
OUT_PNG = (_REPO / "results/synthetic_cardinal/"
           "ttb_generator_check.png")
NOISES = (0.0, 0.05, 0.3)
N_SUBJ_MODEL = 400


def load_experiment(run_dir, round_idx=0, obs_idx=0):
    st = json.loads((run_dir / "observations" / "state.json").read_text())
    obs = st["rounds"][round_idx]["observations"][obs_idx]
    exp = obs["experiment"]
    data_file = next((run_dir / "observations" / "data").glob(
        f"round_{round_idx:03d}_obs_{obs_idx:02d}.jsonl"))
    return exp, data_file


def empirical_pb(data_file):
    """Pool trials -> (pairs, empirical P(B), n_trials per pair)."""
    counts: dict[tuple, list[int]] = {}
    order: list[tuple] = []
    for line in Path(data_file).read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        a = tuple(int(x) for x in rec["option_a_ratings"])
        b = tuple(int(x) for x in rec["option_b_ratings"])
        key = (a, b)
        if key not in counts:
            counts[key] = [0, 0]; order.append(key)
        counts[key][0] += int(rec["response"]); counts[key][1] += 1
    pb = np.array([counts[k][0] / counts[k][1] for k in order])
    n = np.array([counts[k][1] for k in order])
    return order, pb, n


def sim_pb(theory, pairs, *, validities, rating_max, n_subj, seed,
           action_noise=0.0):
    """Per-stimulus P(choose B). Base choice = argmax(predict); with prob
    `action_noise` a uniform coin (ε-greedy, mirrors src/experiment.py:173)."""
    random.seed(seed)
    noise_rng = np.random.default_rng(seed)
    ctx = {"n_features": len(validities), "n_labels": 2,
           "validities": list(validities), "rating_max": int(rating_max)}
    acc = np.zeros(len(pairs))
    for _ in range(n_subj):
        params = theory.sample_parameters(ctx)
        for j, (a, b) in enumerate(pairs):
            probs = np.asarray(theory.predict(
                params, np.array([a, b], dtype=float), EMPTY_HISTORY))
            if action_noise > 0.0 and noise_rng.random() < action_noise:
                acc[j] += int(noise_rng.integers(0, len(probs)))
            else:
                acc[j] += int(np.argmax(probs))
    return acc / n_subj


def pearson(x, y):
    x = np.asarray(x); y = np.asarray(y)
    if x.std() == 0 or y.std() == 0:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def mse(x, y):
    return float(np.mean((np.asarray(x) - np.asarray(y)) ** 2))


def _push(store, noise, role, val):
    store.setdefault(noise, {}).setdefault(role, []).append(val)


def main():
    canon_ttb = Theory.from_yaml(YAML_DIR / "ttb.yaml")
    rand_ttb = Theory.from_yaml(YAML_DIR / "ttb.yaml")
    rand_ttb.parameters["validities"] = "[(0.0, 1.0)] * n_features"

    noise_dirs = {float(d.name.removeprefix("noise=")): d
                  for d in sorted(TTB_ROOT.glob("noise=*")) if d.is_dir()}
    agg_r: dict[float, dict[str, list[float]]] = {}
    agg_m: dict[float, dict[str, list[float]]] = {}

    for noise in NOISES:
        noise_dir = noise_dirs.get(noise)
        runs = sorted(noise_dir.glob("hdm_ground_truth_ttb_*_run*")) if noise_dir else []
        print(f"=== noise={noise:g}  ({len(runs)} runs)")
        for run in runs:
            exp, data_file = load_experiment(run)
            validities = [float(v) for v in exp["validities"]]
            rating_max = int(exp["rating_max"])
            pairs, data, n = empirical_pb(data_file)

            canon = sim_pb(canon_ttb, pairs, validities=validities,
                           rating_max=rating_max, n_subj=N_SUBJ_MODEL, seed=0,
                           action_noise=noise)
            rand = sim_pb(rand_ttb, pairs, validities=validities,
                          rating_max=rating_max, n_subj=N_SUBJ_MODEL, seed=0,
                          action_noise=noise)

            rc, mc = pearson(data, canon), mse(data, canon)
            rr, mr = pearson(data, rand), mse(data, rand)
            _push(agg_r, noise, "canon", rc); _push(agg_m, noise, "canon", mc)
            _push(agg_r, noise, "rand", rr); _push(agg_m, noise, "rand", mr)
            print(f"    {run.name[-4:]}  val={validities} "
                  f"| {len(pairs)} stim, {int(n.sum())} trials")
            print(f"        data vs CANONICAL TTB    r={rc:+.3f}  mse={mc:.4f}")
            print(f"        data vs randomized-cue   r={rr:+.3f}  mse={mr:.4f}")
        print()

    plot(agg_r, agg_m, OUT_PNG)


ROLE_ORDER = ("canon", "rand")
ROLE_LABEL = {"canon": "data vs canonical TTB",
              "rand": "data vs randomized-cue TTB"}
ROLE_COLOR = {"canon": "#C44E52", "rand": "#8172B2"}


def _mean_sem(vals):
    vals = [v for v in vals if not np.isnan(v)]
    if not vals:
        return np.nan, 0.0
    m = float(np.mean(vals))
    s = float(np.std(vals, ddof=1) / np.sqrt(len(vals))) if len(vals) > 1 else 0.0
    return m, s


def plot(agg_r, agg_m, out_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    noises = sorted(agg_r)
    x = np.arange(len(noises))
    width = 0.8 / len(ROLE_ORDER)
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.4), sharex=True)

    for ax, agg, ylab, ttl in [
        (axes[0], agg_r, "Pearson r (empirical data vs model)", "Correlation"),
        (axes[1], agg_m, "MSE (empirical data vs model, lower=better)", "MSE"),
    ]:
        for i, role in enumerate(ROLE_ORDER):
            means = np.array([_mean_sem(agg[n].get(role, []))[0]
                              for n in noises], dtype=float)
            sems = np.array([_mean_sem(agg[n].get(role, []))[1]
                             for n in noises], dtype=float)
            ax.bar(x - 0.4 + width * (i + 0.5), means, width,
                   yerr=sems, capsize=2, color=ROLE_COLOR[role],
                   edgecolor="black", linewidth=0.3,
                   label=ROLE_LABEL[role] if ax is axes[0] else None)
        ax.set_xticks(x)
        ax.set_xticklabels([f"{n:g}" for n in noises])
        ax.set_xlabel("ground-truth action noise (ε)")
        ax.set_ylabel(ylab)
        ax.set_title(ttl)
        ax.grid(axis="y", linestyle=":", linewidth=0.4, alpha=0.5)
        ax.set_axisbelow(True)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[0].axhline(0.0, color="0.4", linewidth=0.8)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=len(ROLE_ORDER),
               bbox_to_anchor=(0.5, -0.02), frameon=False)
    fig.suptitle("Which TTB generated the data? Empirical choice proportions "
                 "vs candidate generators (mean ± SEM across runs)", fontsize=11)
    fig.tight_layout(rect=(0, 0.05, 1, 0.95))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[plot] wrote {out_path}")


if __name__ == "__main__":
    main()
